[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 %(ENV_VNC_SCREEN)s +extension RANDR
user=chrome
autorestart=true
priority=100

[program:chromedriver]
environment=HOME="/home/chrome",DISPLAY=":1",USER="chrome"
command=/bin/chromedriver --port=9515 --verbose --allowed-ips=""
user=chrome
autorestart=true
priority=200

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 %(ENV_X11VNC_AUTH)s -wait 5 -forever -xrandr
user=chrome
autorestart=true
priority=300
